# This is a helper utility to generate list of all sub jobs in multijob

print '''#
# DO NOT EDIT THIS TEMPLATE MANUALLY
# This configuration is autogenerated by helper script.
#
- job-template:
    name: '{pipeline}.{branch}.vms.runner'
    project-type: multijob
    description: |
      Entry point

    node: runner
    concurrent: true

    parameters:
    # FIXME: Figure out why extended choice created from JJB is not visible..
    - p_PLATFORMS:
        default: 'linux-x64,linux-x86,win-x86'
    - p_CUSTOMIZATIONS:
        default: 'default,hanwha'
    - string:
        name: _NX_VMS_COMMIT
        default: '{branch}'
    - p_CLEAN_BUILD

    wrappers:
    - timestamps
    # note: DO NOT ADD any timeouts here. Put them in corresponding child jobs.

    builders:

    - inject:
        properties-content: |
          BRANCH={branch}
          PIPELINE={pipeline}

    # FIXME: run conditionally when commit is not set

    - multijob:
        name: Freeze nx commit
        projects:
        - name: '{pipeline}.{branch}.vms.freeze_nx_vms_commit'
          kill-phase-on: FAILURE
          predefined-parameters: |
            REQUESTED_BY=${{JOB_NAME}}-${{BUILD_NUMBER}}
            NX_VMS_COMMIT=$_NX_VMS_COMMIT
    - copyartifact:
        project: '{pipeline}.{branch}.vms.freeze_nx_vms_commit'
        filter: 'NX_VMS_COMMIT.envvar'
        which-build: last-successful
        parameter-filters: REQUESTED_BY=${{JOB_NAME}}-${{BUILD_NUMBER}}
    - inject:
        properties-file: 'NX_VMS_COMMIT.envvar'

    - multijob:
        name: Request new release build id
        projects:
        - name: '{pipeline}.build_number.generator'
          kill-phase-on: FAILURE
          predefined-parameters: |
            REQUESTED_BY=${{JOB_NAME}}-${{BUILD_NUMBER}}
    - copyartifact:
        project: '{pipeline}.build_number.generator'
        filter: 'BUILD_IDENTITY.envvar'
        which-build: last-successful
        parameter-filters: REQUESTED_BY=${{JOB_NAME}}-${{BUILD_NUMBER}}
    - inject:
        properties-file: 'BUILD_IDENTITY.envvar'

    # At this point we know BUILD_IDENTITY and NX_VMS_COMMIT, so build-name may be set.
    - build-name-setter:
        template: '[${{BUILD_ID}}] ${{BRANCH}}-${{BUILD_IDENTITY}}@${{NX_VMS_COMMIT}}'
        macro: true

    - multijob:
        name: Build web admin
        projects:
        - name: '{pipeline}.{branch}.vms.webadmin.universal.build'
          kill-phase-on: FAILURE
          predefined-parameters: |
            BUILD_IDENTITY=$BUILD_IDENTITY
            NX_VMS_COMMIT=$NX_VMS_COMMIT
            CLEAN_BUILD=$CLEAN_BUILD

    - multijob:
        name: Run all VMS distribution related jobs
        projects:'''

for platform in ("linux-x64 linux-x86 bananapi bpi rpi edge1 "
                 "tx1 android-arm win-x64 win-x86 mac ios").split():
    for customization in ("default default_cn default_zh_CN cox "
                          "digitalwatchdog digitalwatchdog_global hanwha "
                          "ipera ionetworks nutech ras senturian systemk "
                          "tricom ust vista vmsdemoblue vmsdemoorange").split():

        # below is template for skipping non-desired intersections.
        # if platform == "--1--" and customization == "--2--": continue

        if platform == "edge1" and customization != "digitalwatchdog":
            continue

        print '''
        - name: '{pipeline}.{branch}.vms.installer.'''+platform+'''.'''+customization+'''.all'
          kill-phase-on: NEVER
          enable-condition: >-
            ("$PLATFORMS     ").trim().split(",").contains("'''+platform+'''") &&
            ("$CUSTOMIZATIONS").trim().split(",").contains("'''+customization+'''")
          predefined-parameters: |
            BUILD_IDENTITY=$BUILD_IDENTITY
            NX_VMS_COMMIT=$NX_VMS_COMMIT
            CLEAN_BUILD=$CLEAN_BUILD
'''
print '''
    # At this moment all builds are completed and we may publish links
    - inject:
        properties-content: |
          REPOSITORY_URL={artifact_repository_base_url}/{artifact_location_root_pattern}
          JUNKSHOP_URL={junkshop_base_url}/{junkshop_location_root_pattern}
    - set-build-description
'''
