delete from artifact cascade;
delete from run cascade;
delete from test cascade;
delete from artifacttype cascade;
delete from branch cascade;
delete from platform cascade;
delete from cloudgroup cascade;
delete from customization cascade;
delete from artifacttype cascade;
