drop table artifact cascade;
drop table run cascade;
drop table test cascade;
drop table artifacttype cascade;
drop table branch cascade;
drop table platform cascade;
drop table cloudgroup cascade;
drop table customization cascade;
drop table artifacttype cascade;
