drop table artifact cascade;
drop table run cascade;
drop table test cascade;
drop table branch cascade;
drop table platform cascade;
drop table cloud_group cascade;
drop table customization cascade;
drop table project cascade;
drop table artifact_type cascade;
