#!/usr/bin/env python
"""
    unittest_make_backtraces
    ~~~~~~~~~~~~~~~~~~~~~~~~

    It's a script to process crash files and collect backtraces into unittests working directory.
    RUN THE SCRIPT ON THE NODE, WHERE THE UNITTESTS HAVE BEEN RAN, ONLY.
"""
import argparse
import logging
from pathlib2 import Path
from junk_shop.unittest.make_backtraces import make_backtraces


def setup_logging(level=None):
    format = '%(asctime)-15s %(levelname)-7s %(message)s'
    logging.basicConfig(level=level or logging.INFO, format=format)


def main():
    parser = argparse.ArgumentParser(
        usage='%(prog)s [options]')
    parser.add_argument(
        '--work-dir', required=True,
        help='Unittests working directory. '
             'The directory should contain unittests prerequisites, '
             'generated by unittest_run script')
    args = parser.parse_args()
    setup_logging()
    make_backtraces(Path(args.work_dir))


if __name__ == "__main__":
    main()
